# Generated by Django 2.2.5 on 2019-09-18 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0001_squashed_0021'),
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactpage',
            name='banner_image',
            field=models.ForeignKey(null=True, on_delete='models.SET_NULL', related_name='+', to='wagtailimages.Image'),
        ),
    ]
