# Generated by Django 2.2.4 on 2019-08-30 22:01

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('wagtailimages', '0001_squashed_0021'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogDetailPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('custom_title', models.CharField(help_text='Overwrites the default title', max_length=120)),
                ('description', models.CharField(help_text='Description which will appear in the listing', max_length=300)),
                ('author', models.CharField(blank=True, max_length=100, null=True)),
                ('content', wagtail.core.fields.RichTextField()),
                ('banner_image', models.ForeignKey(null=True, on_delete='models.SET_NULL', related_name='+', to='wagtailimages.Image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
