# Generated by Django 2.2.4 on 2019-08-31 15:46

from django.db import migrations
import streamfs.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogdetailpage',
            name='streams',
            field=wagtail.core.fields.StreamField([('full_richtext', streamfs.blocks.RichTextBlock())], blank=True, null=True),
        ),
    ]
