# Generated by Django 2.2.4 on 2019-08-31 15:53

from django.db import migrations
import streamfs.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogdetailpage_streams'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogdetailpage',
            name='streams',
            field=wagtail.core.fields.StreamField([('full_richtext', streamfs.blocks.RichTextBlock()), ('code_block', streamfs.blocks.CodeBlock())], blank=True, null=True),
        ),
    ]
