# Generated by Django 2.2.4 on 2019-08-31 17:40

from django.db import migrations
import streamfs.blocks
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190831_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogdetailpage',
            name='streams',
            field=wagtail.core.fields.StreamField([('full_richtext', streamfs.blocks.RichTextBlock()), ('code_block', streamfs.blocks.CodeBlock()), ('single_image', wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(required=True)), ('caption', wagtail.core.blocks.CharBlock(max_length=250, null=True, required=False))]))], blank=True, null=True),
        ),
    ]
