# Generated by Django 2.2.4 on 2019-09-02 22:20

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20190902_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcategory',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(allow_unicode=True, blank=True, editable=False, help_text='This is the url of the category', populate_from='name'),
        ),
        migrations.AlterField(
            model_name='bloglistingpage',
            name='custom_title',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
