# Generated by Django 2.2.4 on 2019-09-04 02:27

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20190902_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogdetailpage',
            name='content',
            field=wagtail.core.fields.RichTextField(blank=True, null=True),
        ),
    ]
