# Generated by Django 2.2.5 on 2019-09-18 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_bloglistingpage_intro_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bloglistingpage',
            old_name='custom_title',
            new_name='banner_title',
        ),
    ]
