# Generated by Django 2.2.5 on 2019-09-14 00:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20190830_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='banner_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='banner_title',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
