# Generated by Django 2.2.5 on 2019-09-18 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20190915_1840'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='about_subtitle',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
