# Generated by Django 2.2.5 on 2019-09-18 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flex', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flexiblepage',
            name='banner_subtitle',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
