# Generated by Django 2.2.5 on 2019-09-18 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flex', '0002_flexiblepage_banner_subtitle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flexiblepage',
            name='subtitle',
        ),
    ]
