# Generated by Django 2.2.5 on 2019-09-18 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flex', '0003_remove_flexiblepage_subtitle'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flexiblepage',
            old_name='custom_title',
            new_name='banner_title',
        ),
    ]
