# Generated by Django 2.2.4 on 2019-08-30 20:33

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linkedin', models.URLField(blank=True, help_text='LinkedIn URL', null=True)),
                ('github', models.URLField(blank=True, help_text='Github URL', null=True)),
                ('reddit', models.URLField(blank=True, help_text='Reddit URL', null=True)),
                ('twitter', models.URLField(blank=True, help_text='twitter URL', null=True)),
                ('footertext', wagtail.core.fields.RichTextField(blank=True, null=True)),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.Site')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
