# Generated by Django 2.2.5 on 2019-09-18 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0002_menuitem_highlighted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='highlighted',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
